#cloud-config
hostname: srv-02
manage_etc_hosts: true

apt_update: true
apt_upgrade: false
locale: fr_FR.UTF-8

packages:
  - build-essential
  - gpg
  - zsh

groups:
  - devops

users:
  - name: demo
    groups: sudo,devops
    shell: /bin/zsh
    sudo: [ 'ALL=(ALL) NOPASSWD:ALL' ]
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAZmk9JmH28XMQd+V1vIlNnr0OdAzxrhSVyIrpIM4JIs
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB+jS1XEWDyQULVsU34b1h2OnQD5rChONnuUHcuYWT8T
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOgNblvDTXaSnv/jc6g8x0cqCIsBLcFgPeChcPacs90A


runcmd:
  - systemctl enable ssh
  - systemctl start ssh
