all:
  vars:
    ansible_user: demo
    ansible_ssh_private_key_file: /root/.ssh/private_key
  children:
    all_servers:
      hosts:
        srv-dev-01:
          ansible_host: srv-dev-01.multipass
        srv-dev-02:
          ansible_host: srv-dev-02.multipass
