# https://beszel.dev/guide/agent-installation
name: beszel

services:
  beszel:
    image: henrygd/beszel
    restart: unless-stopped
    networks:
      docker-net:
    volumes:
      - beszel-vol:/beszel_data
    labels:
      traefik.enable: true
      traefik.http.services.beszel-svc.loadbalancer.server.port: 8090
      traefik.http.routers.beszel-rtr.entrypoints: web,websecure
      traefik.http.routers.beszel-rtr.rule: Host(`beszel.lab.victor3spoir.de`)
      traefik.http.routers.beszel-rtr.tls: true
      traefik.http.routers.beszel-rtr.tls.certresolver: spaceship
      traefik.http.routers.beszel-rtr.service: beszel-svc

networks:
  docker-net:
    external: true

volumes:
  beszel-vol:
    name: beszel-vol
    driver: local
