#cloud-config
hostname: srv-worker
manage_etc_hosts: true

apt_update: true
apt_upgrade: false
locale: fr_FR.UTF-8

packages:
  - build-essential
  - gpg
  - zsh

users:
  - name: demo
    groups: sudo
    shell: /bin/zsh
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAZmk9JmH28XMQd+V1vIlNnr0OdAzxrhSVyIrpIM4JIs demo@host
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB+jS1XEWDyQULVsU34b1h2OnQD5rChONnuUHcuYWT8T demo@host


runcmd:
  - echo "starting command"