#cloud-config
# hostname: srv-dev-01
# manage_etc_hosts: true

# ssh_pwauth: false
# apt_update: true
# # apt_upgrade: true
# locale: fr_FR.UTF-8

packages:
  - build-essential
  - gpg
  - zsh
  - docker.io

# groups:
#   - devops

# users:
#   - name: demo
#     groups: sudo,docker,devops
#     shell: /bin/zsh
#     sudo: ['ALL=(ALL) NOPASSWD:ALL']
#     ssh-authorized-keys:
#       - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAZmk9JmH28XMQd+V1vIlNnr0OdAzxrhSVyIrpIM4JIs

# runcmd:
#   - systemctl enable docker
#   - systemctl start docker
