services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    networks:
      docker-net:
    labels:
      ofelia.enable: true
      ofelia.job-exec.nginx.schedule: "@every 1m"
      ofelia.job-exec.nginx.command: "head -c 23 /dev/random | base64 >> '$( date +%Y%m%d_%H%H).txt'"